language: python

python:
  - "3.5"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install tox
  - pip install coveralls

script:
- tox

env:
  matrix:
  - TOXENV=py27-django14
  - TOXENV=py27-django1410
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django167
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django16
  - TOXENV=py34-django167
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=flake8
  - TOXENV=coverage

after_success: coveralls

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      ZMA/38RDaVSTvqFLFjVYzNNDf3pCODOEOaLpWuNrsCCzKf1B5bQ7MSRai+9wV4kkEJ2/zLcBU3wUS4Y8W5w8dd9q0xtOHKIBS9xClk25fhEwc
      WlwPARYNv6+iZemfS8a9YBy9sd/4a+901xOzcLYT9urEAPK+v6Q5UUkl3yt4UTyLC6Og+Hbie9Wap8CPh0INNjm1NZjdzrXAPDR4Rd0/PhEkl
      MtFS2u0fKJXm4TG90WnPoD60FfurOcnv/1WiGBYv0FDIXtVvT5xNqzHUDd3RHRKD84Zedt/yFBGDIKKrJ8dUfu2hAf2mAyA+HX5p98K38q/bw
      oaS9zEO9mAeFDbpiI/BNADGB6Hspq9Nm8kORp7Ov5x2FR7G972kmF059O+n0JWDzVf45ELfpmosuDO8Dt8Sm6CQ64MJgxvKl5ApBQJSDYkDoB
      60+llbkzegsPWD5NK616+RLkwtyneWhFdn+rC6JVamw12jbklGTDItE8PfzzqOfs7pGBQE5lYFp3Sdr4s/gD+TEBkUjdcPYKcxtAZJw4KkByH
      n1heO7YRfi5J2PJ8r2fKoJE3m2TRKCxUtAiv2rc3Zf5caYm5izUapINYMGruduCHfz3HleLYMTtHmjRNh355QohgeOAncJ7HYws4gHgHB2ECC
      GpPO3WBXXc2thQFApRKC0vjXhTB8c=
  on:
    # Warning: With this config, the package is released on pypi after the first matrix job succeeeds. This is currently fine
    #           since we shouldn't create tags before a successful build. Travis plans to add after_success callback in Q1/Q2 of
    #           2017. See https://github.com/travis-ci/travis-ci/issues/929 for more info.
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/django-thorbanks

notifications:
  email: false
